export const FETCH_ALL_IMAGES_PENDING = "FETCH_ALL_IMAGES_PENDING";
export const FETCH_ALL_IMAGES_SUCCESS = "FETCH_ALL_IMAGES_SUCCESS";
export const FETCH_ALL_IMAGES_FAILED = "FETCH_ALL_IMAGES_FAILED";

export const ADD_NEW_IMAGE_PENDING = "ADD_NEW_IMAGE_PENDING";
export const ADD_NEW_IMAGE_SUCCESS = "ADD_NEW_IMAGE_SUCCESS";
export const ADD_NEW_IMAGE_FAILED = "ADD_NEW_IMAGE_FAILED";

export const DELETE_IMAGE_PENDING = "DELETE_IMAGE_PENDING";
export const DELETE_IMAGE_SUCCESS = "DELETE_IMAGE_SUCCESS";
export const DELETE_IMAGE_FAILED = "DELETE_IMAGE_FAILED";

export const UPDATE_IMAGE_PENDING = "UPDATE_IMAGE_PENDING";
export const UPDATE_IMAGE_SUCCESS = "UPDATE_IMAGE_SUCCESS";
export const UPDATE_IMAGE_FAILED = "UPDATE_IMAGE_FAILED";

export const FETCH_IMAGE_PENDING = "FETCH_IMAGE_PENDING";
export const FETCH_IMAGE_SUCCESS = "FETCH_IMAGE_SUCCESS";
export const FETCH_IMAGE_FAILED = "FETCH_IMAGE_FAILED";
