export const ADD_NEW_CART_ITEM_PENDING = "ADD_NEW_CART_PENDING";
export const ADD_NEW_CART_ITEM_SUCCESS = "ADD_NEW_CART_SUCCESS";
export const ADD_NEW_CART_ITEM_FAILED = "ADD_NEW_CART_FAILED";

export const DELETE_CART_ITEM_PENDING = "DELETE_CART_PENDING";
export const DELETE_CART_ITEM_SUCCESS = "DELETE_CART_SUCCESS";
export const DELETE_CART_ITEM_FAILED = "DELETE_CART_FAILED";

export const UPDATE_CART_PENDING = "UPDATE_CART_PENDING";
export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS";
export const UPDATE_CART_FAILED = "UPDATE_CART_FAILED";

export const UPDATE_CART_TOTAL_SUCCESS = "UPDATE_CART_TOTAL_SUCCESS";

export const FETCH_CART_PENDING = "FETCH_CART_PENDING";
export const FETCH_CART_SUCCESS = "FETCH_CART_SUCCESS";
export const FETCH_CART_FAILED = "FETCH_CART_FAILED";
